"use client";

import { useCallback, useEffect, useState } from "react";
import { PartnerShell, PtnCard, PtnLabel, PtnPill } from "../../../src/components/gmb/PartnerShell";
import { api, ApiClientError } from "../../../src/lib/api";

interface SmtpData {
  partner: { host: string | null; port: number; secure: boolean; user: string | null; fromEmail: string | null; fromName: string | null; passwordLast4: string | null } | null;
  fallback: { source: string; host: string; fromEmail: string } | null;
}
const inputCls = "rounded-control border border-ptn-line bg-ptn-bg px-3 py-2 text-sm2 text-ptn-ink outline-none placeholder:text-ptn-subtle focus:border-ptn-accent";

export default function PartnerSmtpPage() {
  const [data, setData] = useState<SmtpData | null>(null);
  const [host, setHost] = useState(""); const [port, setPort] = useState("587"); const [user, setUser] = useState(""); const [password, setPassword] = useState(""); const [fromEmail, setFromEmail] = useState(""); const [fromName, setFromName] = useState("");
  const [testTo, setTestTo] = useState(""); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(async () => { try { const value = await api.get<SmtpData>("/api/v1/partner/smtp"); setData(value); if (value.partner) { setHost(value.partner.host ?? ""); setPort(String(value.partner.port)); setUser(value.partner.user ?? ""); setFromEmail(value.partner.fromEmail ?? ""); setFromName(value.partner.fromName ?? ""); } } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Could not load SMTP settings."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy("save"); setError(null); setNotice(null); try { await api.put("/api/v1/partner/smtp", { host: host.trim(), port: Number(port) || 587, ...(user.trim() ? { user: user.trim() } : {}), ...(password ? { password } : {}), fromEmail: fromEmail.trim(), ...(fromName.trim() ? { fromName: fromName.trim() } : {}) }); setPassword(""); setNotice("SMTP settings saved and active for your branded email."); await load(); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Could not save SMTP settings."); } finally { setBusy(null); } }
  async function remove() { if (!window.confirm("Delete your saved SMTP settings and fall back to platform email?")) return; setBusy("delete"); setError(null); try { await api.delete("/api/v1/partner/smtp"); setHost(""); setPort("587"); setUser(""); setPassword(""); setFromEmail(""); setFromName(""); setNotice("Partner SMTP settings deleted."); await load(); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Could not delete SMTP settings."); } finally { setBusy(null); } }
  async function test(event: React.FormEvent) { event.preventDefault(); setBusy("test"); setError(null); setNotice(null); try { const result = await api.post<{ ok: boolean; message: string }>("/api/v1/partner/smtp/test", { to: testTo.trim() }); if (result.ok) setNotice(result.message); else setError(result.message); } catch (reason) { setError(reason instanceof ApiClientError ? reason.message : "Could not send the test email."); } finally { setBusy(null); } }
  const active = data?.partner ? "partner" : data?.fallback ? "fallback" : "off";
  return (
    <PartnerShell title="SMTP">
      {error ? <div className="mb-3.5 rounded-control border border-gmb-danger/30 bg-gmb-danger/10 px-3 py-2 text-sm2 text-ptn-danger">{error}</div> : null}{notice ? <div className="mb-3.5 rounded-control border border-ptn-accent/30 bg-ptn-accent/10 px-3 py-2 text-sm2 text-ptn-accent">{notice}</div> : null}
      <div className="mb-3.5 grid grid-cols-2 gap-3.5"><PtnCard><div className="flex justify-between gap-3"><div><PtnLabel>Delivery status</PtnLabel><div className="mt-2 text-xs2 text-ptn-muted">{active === "partner" ? `${data?.partner?.host}:${data?.partner?.port} · from ${data?.partner?.fromEmail}` : active === "fallback" ? `Using ${data?.fallback?.source} fallback · ${data?.fallback?.host}` : "Email is off until a relay is configured."}</div></div><PtnPill tone={active === "off" ? "warn" : "ok"}>{active === "partner" ? "Using partner SMTP" : active === "fallback" ? "Using fallback" : "Off"}</PtnPill></div></PtnCard><PtnCard><PtnLabel>Credential storage</PtnLabel><div className="mt-2 text-xs2 leading-relaxed text-ptn-muted">The password is encrypted in your partner Secret Vault scope and never returned. A saved password is shown only by its last four characters.</div></PtnCard></div>
      <PtnCard><form onSubmit={save} className="grid grid-cols-2 gap-3">{[["Host", host, setHost, "smtp.example.com", "text"], ["Port", port, setPort, "587", "text"], ["User (optional)", user, setUser, "apikey", "text"], [`Password ${data?.partner?.passwordLast4 ? `(saved ••••${data.partner.passwordLast4} — leave empty to keep)` : ""}`, password, setPassword, "••••••••", "password"], ["From address", fromEmail, setFromEmail, "no-reply@yourdomain.com", "email"], ["From name", fromName, setFromName, "Your agency", "text"]].map(([label, value, setter, placeholder, type]) => <label key={String(label)} className="flex flex-col gap-1"><span className="font-geist-mono text-micro uppercase tracking-[0.08em] text-ptn-subtle">{label as string}</span><input value={value as string} onChange={(event) => (setter as (value: string) => void)(event.target.value)} placeholder={placeholder as string} type={type as string} required={label === "Host" || label === "Port" || label === "From address"} className={inputCls}/></label>)}<div className="col-span-2 flex justify-between pt-1"><span className="text-xs2 text-ptn-muted">Port 465 uses implicit TLS; 587 upgrades with STARTTLS.</span><div className="flex gap-2">{data?.partner ? <button type="button" disabled={busy !== null} onClick={() => void remove()} className="rounded-control border border-ptn-line px-4 py-2 text-sm2 font-medium text-ptn-danger hover:bg-gmb-danger/10 disabled:opacity-50">Delete</button> : null}<button type="submit" disabled={busy !== null || !host.trim() || !fromEmail.trim()} className="rounded-control bg-ptn-accent px-4 py-2 text-sm2 font-semibold text-ptn-bg disabled:opacity-50">{busy === "save" ? "Saving…" : "Save configuration"}</button></div></div></form></PtnCard>
      <PtnCard className="mt-3.5"><form onSubmit={test} className="flex items-end gap-2"><label className="flex flex-1 flex-col gap-1"><span className="font-geist-mono text-micro uppercase tracking-[0.08em] text-ptn-subtle">Send a real test email</span><input value={testTo} onChange={(event) => setTestTo(event.target.value)} type="email" required placeholder="you@example.com" className={inputCls}/></label><button type="submit" disabled={busy !== null || !testTo.trim()} className="rounded-control border border-ptn-line px-4 py-2 text-sm2 font-semibold text-ptn-ink hover:bg-ptn-panel-hover disabled:opacity-50">{busy === "test" ? "Sending…" : "Send test"}</button></form></PtnCard>
    </PartnerShell>
  );
}
