// ============================================================================
// GMB report PDF renderer (planning PDF §3 Reports: "Download PDF reports").
//
// Uses PDFKit directly so every download and scheduled attachment is a real,
// consistently rendered A4 document.
// ============================================================================

import PDFDocument from "pdfkit";

interface ReportLike {
  id: string;
  type: string;
  periodStart: Date | string;
  periodEnd: Date | string;
  summary: string | null;
  actionPlan: unknown;
  data?: unknown;
  createdAt: Date | string;
}

interface ReportRenderInput {
  report: ReportLike;
  /** Brand shown in the header and footer. Defaults to "Adgrowly GMB". */
  issuerName?: string;
}

const fmtDate = (d: Date | string) => new Date(d).toISOString().slice(0, 10);

interface TrendLike {
  momentum?: string;
  reviewsCount?: number;
  averageRating?: number;
  totalViews?: number;
  totalActions?: number;
  top3?: number;
}

function trendFrom(data: unknown): TrendLike | null {
  if (!data || typeof data !== "object") return null;
  const t = (data as Record<string, unknown>).trend;
  return t && typeof t === "object" ? (t as TrendLike) : null;
}

function actionItems(plan: unknown): Array<{ priority?: string; task?: string }> {
  return Array.isArray(plan) ? (plan as Array<{ priority?: string; task?: string }>) : [];
}

const signed = (n: number | undefined) => (n == null ? "0" : n > 0 ? `+${n}` : `${n}`);

/**
 * Plain-text content source for the PDF. Exported for tests so the report
 * shape is pinned independently from PDFKit's binary encoding.
 */
export function buildReportPdfLines(input: ReportRenderInput): string[] {
  const r = input.report;
  const issuer = input.issuerName ?? "Adgrowly GMB";
  const trend = trendFrom(r.data);
  const plan = actionItems(r.actionPlan);
  const lines = [
    `${issuer} — Google Business performance report`,
    `Type: ${r.type} · Period: ${fmtDate(r.periodStart)} to ${fmtDate(r.periodEnd)}`,
    `Generated: ${fmtDate(r.createdAt)}`,
    "",
  ];
  if (r.summary) lines.push("Summary:", ...wrapText(r.summary, 95), "");
  if (trend) {
    lines.push(
      `Vs last period (${trend.momentum ?? "steady"}): ${signed(trend.reviewsCount)} reviews · ` +
        `${signed(trend.averageRating)} rating · ${signed(trend.totalViews)} views · ` +
        `${signed(trend.totalActions)} actions · ${signed(trend.top3)} top-3`,
      "",
    );
  }
  if (plan.length > 0) {
    lines.push("Action plan:");
    for (const item of plan) {
      lines.push(`  [${(item.priority ?? "low").toUpperCase()}] ${item.task ?? ""}`);
    }
  }
  return lines;
}

/** Greedy word-wrap so long narratives stay inside the PDF page. */
export function wrapText(text: string, width: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const out: string[] = [];
  let line = "";
  for (const w of words) {
    if (line && line.length + 1 + w.length > width) {
      out.push(line);
      line = w;
    } else {
      line = line ? `${line} ${w}` : w;
    }
  }
  if (line) out.push(line);
  return out;
}

/** Render a complete A4 PDF into memory for download or email attachment. */
export async function renderGmbReportPdf(input: ReportRenderInput): Promise<Buffer> {
  return renderWithPdfkit(input);
}

async function renderWithPdfkit(input: ReportRenderInput): Promise<Buffer> {
  const issuer = input.issuerName ?? "Adgrowly GMB";

  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (e: Error) => reject(e));

    const [title, ...rest] = buildReportPdfLines(input);
    doc.fontSize(16).text(title);
    doc.moveDown();
    doc.fontSize(10);
    for (const line of rest) {
      if (line === "") doc.moveDown(0.5);
      else doc.text(line);
    }
    doc.moveDown(2);
    doc.fontSize(8).fillColor("#666").text(`Generated by ${issuer}.`, { align: "center" });
    doc.end();
  });
}
